### ISSUE TITLE
Add Referrer-Policy

### ISSUE THREAD

**Issue by deg4uss3r** [rustasync/armor#1]
# Feature Request
## Summary
Add the Referrer-Policy header which helps protect the site from XSS attacks by controlling how users are directed from the site. 

## Motivation
Good newer security header to add to the baseline for users of `armor`. 

## Guide-level explanation
Using the `enum` option set the `Referrer-Policy` to one of the possible options described in the standard that allows referrers from the site. 

## Resources
- [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) 
- [Scott Helme](https://scotthelme.co.uk/a-new-security-header-referrer-policy/)

**Comment by yoshuawuyts** [comment]
@deg4uss3r this seems great! Would you like to contribute a patch for this?

As per https://helmetjs.github.io/docs/ this is not enabled by default, perhaps we should not include it as part of `armor::armor` -- what do you think?

**Comment by deg4uss3r** [comment]
Yeah I could submit a patch! Should we have a new module for optional headers then?

**Comment by yoshuawuyts** [comment]
@deg4uss3r probably just a new function, but not include it by default in `armor::armor` I'd say!

**Comment by yoshuawuyts** [comment]
Closed by #2
